name: LobbySpawn
version: ${project.version}
main: koral.lobbyspawn.LobbySpawn
api-version: 1.13
authors: [koral]
description: lobbyspawn
commands:
  setspawn:
    permission: lobbyspawn.setspawn
  spawn:
